package com.metco.componentsDesign;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

import org.jdesktop.swingx.prompt.PromptSupport;
import org.jdesktop.swingx.search.ListSearchable;

import com.metco.store.Inventory;
import com.metco.store.Product;

public class ComponentsGUI extends javax.swing.JFrame {

    /**
     * Creates new form ComponentsGUI
     */
    public ComponentsGUI(Inventory inventory) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void initComponents() {

        setTitle("Metco Store - Inventory Management");
        ImageIcon logo = new ImageIcon("./src/main/java/com/metco/img/metco_store_logo.jpg");
        setIconImage(logo.getImage());
        JLabel logoLabel = new JLabel(logo);
        getContentPane().add(logoLabel, BorderLayout.NORTH);

        jLabel1 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        inventoryName = new javax.swing.JTextField();
        inventoryPrice = new javax.swing.JTextField();
        inventoryQuantity = new javax.swing.JTextField();
        inventoryMonth = new javax.swing.JTextField();
        inventoryDay = new javax.swing.JTextField();
        inventoryYear = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProducts = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        sortBox = new javax.swing.JComboBox<>();
        searchBar = new javax.swing.JTextField(); 

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inventoryName, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(inventoryPrice)
                    .addComponent(inventoryQuantity)
                    .addComponent(inventoryMonth)
                    .addComponent(inventoryDay)
                    .addComponent(inventoryYear))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inventoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        
        jScrollPane1.setViewportView(listProducts);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        addBtn.setText("Add");

        updateBtn.setText("Update");

        removeBtn.setText("Remove");
        

        sortBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort Name", "Sort Price", "Sort Quantity", "Sort ExpDate" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchBar, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortBox, 0, 122, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn)
                    .addComponent(updateBtn)
                    .addComponent(removeBtn)
                    .addComponent(sortBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Color customColorBackground = new Color(190, 36, 1);
        Color customColorBtn = new Color(81, 2, 7);
        Color customColorBox = new Color(25, 25, 25);
        Color customColorWhite = new Color(215, 215, 210);


        jPanel1.setBackground(customColorBox);
        jPanel2.setBackground(customColorBox);
        jPanel3.setBackground(customColorBox);

        

        MainPanel.setBackground(customColorBackground);

        String invPHSearch = " Search Product";
        String invPHName = " Product Name";
        String invPHPrice = " Product Price";
        String invPHQuantity = " Product Quantity";
        String invPHMonth = " Expire Month";
        String invPHDay = " Expire Day";
        String invPHYear = " Expire Year";

        PromptSupport.setPrompt(invPHName, inventoryName);
        PromptSupport.setPrompt(invPHPrice, inventoryPrice);
        PromptSupport.setPrompt(invPHQuantity, inventoryQuantity);
        PromptSupport.setPrompt(invPHMonth, inventoryMonth);
        PromptSupport.setPrompt(invPHDay, inventoryDay);
        PromptSupport.setPrompt(invPHYear, inventoryYear);
        PromptSupport.setPrompt(invPHSearch, searchBar);

        Color promptColor = new Color(100, 100, 100); // Light gray color for prompts
        PromptSupport.setForeground(promptColor, inventoryName);
        PromptSupport.setForeground(promptColor, inventoryPrice);
        PromptSupport.setForeground(promptColor, inventoryQuantity);
        PromptSupport.setForeground(promptColor, inventoryMonth);
        PromptSupport.setForeground(promptColor, inventoryDay);
        PromptSupport.setForeground(promptColor, inventoryYear);
        PromptSupport.setForeground(promptColor, searchBar);

        PromptSupport.setFontStyle(Font.BOLD, searchBar);
        PromptSupport.setFontStyle(Font.BOLD, inventoryName);
        PromptSupport.setFontStyle(Font.BOLD, inventoryPrice);
        PromptSupport.setFontStyle(Font.BOLD, inventoryQuantity);
        PromptSupport.setFontStyle(Font.BOLD, inventoryMonth);
        PromptSupport.setFontStyle(Font.BOLD, inventoryDay);
        PromptSupport.setFontStyle(Font.BOLD, inventoryYear);

        addBtn.setBackground(customColorBtn);
        removeBtn.setBackground(customColorBtn);
        updateBtn.setBackground(customColorBtn);
        sortBox.setBackground(customColorBtn);

        addBtn.setForeground(customColorWhite);
        removeBtn.setForeground(customColorWhite);
        updateBtn.setForeground(customColorWhite);
        sortBox.setForeground(customColorWhite);
        
        inventoryMonth.setBackground(customColorWhite);
        inventoryDay.setBackground(customColorWhite);
        inventoryYear.setBackground(customColorWhite);
        inventoryName.setBackground(customColorWhite);
        inventoryPrice.setBackground(customColorWhite);
        inventoryQuantity.setBackground(customColorWhite);
        searchBar.setBackground(customColorWhite);

        listProducts.setBackground(customColorWhite);

        pack();
        setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel MainPanel;
    public javax.swing.JTextField inventoryDay;
    public javax.swing.JTextField inventoryMonth;
    public javax.swing.JTextField inventoryName;
    public javax.swing.JTextField inventoryPrice;
    public javax.swing.JTextField inventoryQuantity;
    public javax.swing.JTextField inventoryYear;
    public javax.swing.JButton addBtn;
    public javax.swing.JButton updateBtn;
    public javax.swing.JButton removeBtn;
    public javax.swing.JComboBox<String> sortBox;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JList<Product> listProducts;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JTextField searchBar;
}